### ISSUE TITLE
BCD is not used to bootstrap contracts in subsequent attempts

### ISSUE THREAD

**Issue by damian0815** [tzConnectBerlin/que-pasa#40]
Hi folks, first i wanted to say that Que Pasa is great and does exactly what i need it to do.

This issue is to report that the BCD support seems to be inconsistently applied to initialise contracts. Digging in to the code a little, it seems that BCD fast start is only used when `exec_new_contracts_historically` is called - which can only ever be called the very first time that Que Pasa encounters a new contract address.

What this means is that if the initial contract fetch fails and has to be interrupted for whatever reason (eg running out of available database connections to google cloud SQL, which was my issue just now), subsequent contract fetches will just ignore the `--bcd-enable` flag and fetch every single blockchain level. To get BCD fast-start working again I have to pass `--reinit`, but this of course forces all of the contracts to be reinitialised, not just the one that failed.

I'm new to rust so I didn't feel confident making my own fixes, but at a guess it looks like the call to `executor.exec_missing_contracts()` on line 145 of `main.rs` ought to instead apply the same BCD logic as seen in `highlevel.rs` `exec_new_contracts_historically()`. (Perhaps line 145 of `main.rs` could just call `exec_new_contracts_historically()` instead?)

**Comment by RKlompUU** [comment]
Hi Damian, you're right! BCD can be applied in a similar way in `exec_missing_levels`. I'll add it into there.

On a general note, great to hear it does what you are looking for, and if you don't mind we'd be interested to know more about how you're using it and what we could do to make it more useful to you.

**Comment by damian0815** [comment]
ahh thanks @RKlompUU - i see you've addressed it in the PR alraedy, nice, thank you!

sure, happy to give feedback/comments - where'd be the best place to do this? 

elsewhere in my project i'm using Google Firestore, which is a noSQL service. so the next thing i have to do to integrate the `_live` data from Que Pasa into that. it would be great if i had some way of configuring Que Pasa to write at least the live data for contract storage directly into Firestore, instead of (or in addition to) postgresql. should i open a more detailed feature request?

**Comment by johnsnewby** [comment]
Hi,

We merged this change. For import to firestore, there is a commercial solution, but if we're to do something then a component which takes the data and transforms it for firestore would be more appropriate, we think. This is the commercial solution, but if you care to collaborate on something, we'd be super happy to do that. Can you tell us more about your requirements?

Thanks again for using que-pasa and for your feedback. We tend to use telegram for communication but we're also on Discord and Slack.

j
